### ISSUE TITLE
RendererException: compile error in:ShaderSource

### ISSUE THREAD

**Issue by wuendsch** [methusalah/OpenRTS#84]
Current Master throws an exception: 

´´´
com.jme3.app.Application handleError
SCHWERWIEGEND: Uncaught exception thrown in Thread[LWJGL Renderer Thread,5,main]
com.jme3.renderer.RendererException: compile error in:ShaderSource[name=matdefs/MyTerrainLighting.frag, defines, type=Fragment, language=GLSL100] error:ERROR: 0:223: '-' does not operate on 'int' and 'float'
ERROR: 0:228: Use of undeclared identifier 'transp'
ERROR: 0:228: '-' does not operate on 'int' and 'float'
ERROR: 0:233: Use of undeclared identifier 'transp'
ERROR: 0:233: '-' does not operate on 'int' and 'float'
ERROR: 0:238: Use of undeclared identifier 'transp'
ERROR: 0:238: '-' does not operate on 'int' and 'float'
ERROR: 0:244: Use of undeclared identifier 'transp'
ERROR: 0:244: '-' does not operate on 'int' and 'float'
ERROR: 0:298: Use of undeclared identifier 'transp'

	at com.jme3.renderer.lwjgl.LwjglRenderer.updateShaderSourceData(LwjglRenderer.java:1022)
	at com.jme3.renderer.lwjgl.LwjglRenderer.updateShaderData(LwjglRenderer.java:1045)
	at com.jme3.renderer.lwjgl.LwjglRenderer.setShader(LwjglRenderer.java:1111)
	at com.jme3.material.Material.renderMultipassLighting(Material.java:837)
	at com.jme3.material.Material.render(Material.java:1107)
	at com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:523)
	at com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:322)
	at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:380)
	at com.jme3.renderer.RenderManager.renderViewPortQueues(RenderManager.java:782)
	at com.jme3.renderer.RenderManager.flushQueue(RenderManager.java:719)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:983)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1029)
	at app.OpenRTSApplication.update(OpenRTSApplication.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:185)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:228)
	at java.lang.Thread.run(Thread.java:745)

AL lib: (EE) alc_cleanup: 1 device not closed
´´´´

**Comment by wuendsch** [comment]
last commit which is working is e8e9314

**Comment by wuendsch** [comment]
fixed. thx
